name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env: 
  CGO_ENABLED: 1

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18        

    - name: Build
      run: go get github.com/go-git/go-git && go install go.k6.io/xk6/cmd/xk6@latest

    - name: Test
      
      run: xk6 build --with github.com/skibum55/xk6-git

