name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env: 
  CGO_ENABLED: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18        

    - name: Build
      run:  go install go.k6.io/xk6/cmd/xk6@latest # && go install github.com/go-git/go-git/v5@latest

    - name: Test
      
      run: xk6 build --with github.com/skibum55/xk6-git
      
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        version:
          - latest
          - '~> 0.1.1'
        distribution:
          - xk6-git

    steps:
    - name: GoReleaser Action
    # You may pin to the exact commit or the version.
    # uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef
      uses: goreleaser/goreleaser-action@v3.0.0
      with:
        distribution: ${{ matrix.distribution }}
        version: ${{ matrix.version }}
        args: release --skip-publish --rm-dist
        workdir: ./test
